#!/usr/bin/env python3
"""Validate a commit message: Conventional Commits, and no agent attribution.

Run by the lefthook `commit-msg` hook. Stdlib only, so it works before `pnpm install`
has ever been run — the same reason the other tools in this directory have no
dependencies.

Two things are checked:

1. **Conventional Commits.** `type(scope): subject`, imperative, subject <= 72 chars.
   The scope is a layer or module, which keeps `git log --oneline` readable as a map
   of where change lands.

2. **No agent or tool co-authorship trailers.** Commits carry their human author only.
   Several AI tools add `Co-Authored-By` or `Generated with` footers by default; this
   removes the need to remember to strip them.

Usage:
    python tools/check_commit_message.py .git/COMMIT_EDITMSG
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

TYPES = (
    "feat", "fix", "refactor", "perf", "test", "docs", "chore", "build", "ci", "revert",
)

HEADER = re.compile(
    r"^(?P<type>[a-z]+)(?:\((?P<scope>[a-z0-9/._-]+)\))?(?P<breaking>!)?: (?P<subject>.+)$"
)

# Trailers that must never appear. Commits carry their human author only.
FORBIDDEN_TRAILERS = re.compile(
    r"^\s*(co-authored-by:.*(claude|codex|gemini|cursor|copilot|gpt|anthropic|openai|bot)"
    r"|.*generated with .*(claude|codex|cursor|copilot)"
    r"|.*\bco-authored-by:\s*(claude|codex|gemini|cursor|copilot)\b)",
    re.IGNORECASE,
)

MAX_SUBJECT = 72


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: check_commit_message.py <path-to-message-file>", file=sys.stderr)
        return 2

    raw = Path(sys.argv[1]).read_text(encoding="utf8", errors="replace")
    lines = [line for line in raw.splitlines() if not line.startswith("#")]
    while lines and not lines[0].strip():
        lines.pop(0)

    if not lines:
        print("empty commit message")
        return 1

    problems: list[str] = []
    header = lines[0]

    # A merge or revert commit generated by git is left alone.
    if header.startswith(("Merge ", "Revert ")):
        return 0

    match = HEADER.match(header)
    if not match:
        problems.append(
            "header must be  type(scope): subject\n"
            f"    types: {', '.join(TYPES)}\n"
            f"    got:   {header!r}"
        )
    else:
        if match.group("type") not in TYPES:
            problems.append(f"unknown type {match.group('type')!r}; use one of: {', '.join(TYPES)}")
        subject = match.group("subject")
        if len(header) > MAX_SUBJECT:
            problems.append(f"header is {len(header)} characters; keep it within {MAX_SUBJECT}")
        if subject.endswith("."):
            problems.append("subject should not end with a full stop")
        if subject[:1].isupper() and not subject.split()[0].isupper():
            problems.append("subject should start lowercase (it continues the type prefix)")

    if len(lines) > 1 and lines[1].strip():
        problems.append("leave a blank line between the subject and the body")

    for number, line in enumerate(lines, start=1):
        if FORBIDDEN_TRAILERS.match(line):
            problems.append(
                f"line {number}: agent or tool attribution is not allowed in commits\n"
                f"    {line.strip()!r}\n"
                "    Commits carry their human author only."
            )

    if not problems:
        return 0

    print("commit message rejected:\n")
    for problem in problems:
        print(f"  - {problem}")
    print(
        "\nExamples:\n"
        "  feat(core/crm): add lead conversion guard\n"
        "  fix(api/webhooks): stop double-processing duplicate provider events\n"
        "  docs(adr): accept 0002 row-level security\n"
        "\nSee docs/engineering-guardrails.md section 6."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
